### ISSUE TITLE
Doesn't work on Rails 7.0.1

### ISSUE THREAD

**Issue by r7kamura** [makicamel/action_tracer#3]
I encountered the following error on my Rails app:

- action_tracer 0.2.2
- rails 7.0.1
- ruby 2.7.2

```console
$ bundle exec rspec spec/controllers/my_controller_spec.rb

MyController
  #index
     (FAILED - 1)

Failures:

  1) MyController#index succeeds
     Failure/Error: get :index
     
     NoMethodError:
       undefined method `raw_filter' for #<ActiveSupport::Callbacks::Callback:0x00005630adf06cc8>
       Did you mean?  filter
     # /usr/local/bundle/gems/action_tracer-0.2.2/lib/action_tracer/filters.rb:58:in `map'
     # /usr/local/bundle/gems/action_tracer-0.2.2/lib/action_tracer/filters.rb:58:in `block in build'
     # /usr/local/bundle/gems/action_tracer-0.2.2/lib/action_tracer/filters.rb:57:in `each'
     # /usr/local/bundle/gems/action_tracer-0.2.2/lib/action_tracer/filters.rb:57:in `build'
     # /usr/local/bundle/gems/action_tracer-0.2.2/lib/action_tracer/action_tracer.rb:10:in `log'
     # /usr/local/bundle/gems/action_tracer-0.2.2/lib/action_tracer/monkey_patches/abstract_controller/callbacks.rb:8:in `process_action'
     # /usr/local/bundle/gems/actionpack-7.0.1/lib/abstract_controller/base.rb:151:in `process'
     # /usr/local/bundle/gems/actionview-7.0.1/lib/action_view/rendering.rb:39:in `process'
     # /usr/local/bundle/gems/actionpack-7.0.1/lib/action_controller/metal.rb:188:in `dispatch'
     # /usr/local/bundle/gems/actionpack-7.0.1/lib/action_controller/test_case.rb:601:in `block in process_controller_response'
     # /usr/local/bundle/gems/actionpack-7.0.1/lib/action_controller/test_case.rb:593:in `wrap_execution'
     # /usr/local/bundle/gems/actionpack-7.0.1/lib/action_controller/test_case.rb:601:in `process_controller_response'
     # /usr/local/bundle/gems/actionpack-7.0.1/lib/action_controller/test_case.rb:511:in `process'
     # /usr/local/bundle/gems/actionpack-7.0.1/lib/action_controller/test_case.rb:404:in `get'
     # /usr/local/bundle/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
     # ./spec/controllers/my_controller_spec.rb:16:in `block (3 levels) in <top (required)>'

Finished in 1.24 seconds (files took 17.46 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/controllers/my_controller_spec.rb:14 # MyController#index succeeds
```

This is not a reproducible and accurate minimal report, but hopefully it will help with Rails 7.0 support.

**Comment by r7kamura** [comment]
@makicamel Nice work 👍

**Comment by makicamel** [comment]
@r7kamura 
Thank you for your report!!
